import type { Project, Task } from './types';

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    clientName: 'Adebayo Oluwaseun',
    projectTopic: 'Impact of AI on SME Growth in Lagos',
    progress: 75,
    totalAmount: 150000,
    paidAmount: 100000,
    status: 'In Progress',
    deadline: '2024-08-30',
    createdAt: '2024-05-01',
  },
  {
    id: 'proj-2',
    clientName: 'Ngozi Okonjo',
    projectTopic: 'Renewable Energy Adoption in Rural Nigeria',
    progress: 40,
    totalAmount: 120000,
    paidAmount: 50000,
    status: 'Correction',
    deadline: '2024-09-15',
    createdAt: '2024-06-10',
  },
  {
    id: 'proj-3',
    clientName: 'Chinedu Eze',
    projectTopic: 'Fintech Solutions for Financial Inclusion',
    progress: 100,
    totalAmount: 200000,
    paidAmount: 200000,
    status: 'Completed',
    createdAt: '2024-04-15',
  },
  {
    id: 'proj-4',
    clientName: 'Fatima Bello',
    projectTopic: 'E-commerce Trends in Northern Nigeria',
    progress: 10,
    totalAmount: 100000,
    paidAmount: 10000,
    status: 'Pending',
    deadline: '2024-10-01',
    createdAt: '2024-07-01',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Literature Review for Adebayo',
    projectId: 'proj-1',
    projectName: 'Impact of AI on SME Growth in Lagos',
    status: 'In Progress',
    isCorrection: false,
    dueDate: '2024-07-30',
    createdAt: '2024-07-15',
  },
  {
    id: 'task-2',
    title: 'Address feedback for Ngozi (Chapter 2)',
    projectId: 'proj-2',
    projectName: 'Renewable Energy Adoption in Rural Nigeria',
    status: 'To Do',
    isCorrection: true,
    dueDate: '2024-08-05',
    createdAt: '2024-07-20',
  },
  {
    id: 'task-3',
    title: 'Draft methodology for Fatima',
    projectId: 'proj-4',
    projectName: 'E-commerce Trends in Northern Nigeria',
    status: 'To Do',
    isCorrection: false,
    createdAt: '2024-07-22',
  },
  {
    id: 'task-4',
    title: 'Final proofreading for Chinedu',
    projectId: 'proj-3',
    projectName: 'Fintech Solutions for Financial Inclusion',
    status: 'Done',
    isCorrection: false,
    createdAt: '2024-06-01',
  },
];
